apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-bundle-overridingiodv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-bundle-overridingiodv
    app.kubernetes.io/part-of: test-app-peur
  name: build-suite-test-bundle-overridingiodv
  namespace: build-e2e-eugt-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-suite-test-bundle-overridingiodv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-suite-test-bundle-overridingiodv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:3b2ed7a2444d90f69890bacc095812cb26abfbcc856ddba7754167c94fdb428f
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
