apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-bundle-overridingiodv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-bundle-overridingiodv
    app.kubernetes.io/part-of: test-app-peur
  name: build-suite-test-bundle-overridingiodv
  namespace: build-e2e-eugt-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-bundle-overridingiodv
status:
  loadBalancer: {}
